# Generated by Django 3.2.7 on 2021-09-11 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, default='../../../static/images/default.png', null=True, upload_to=''),
        ),
    ]
